name: "Codeville"
markdown: "redcarpet"
highlighter: "pygments"
baseurl: ""
title: "Codeville"

permalink: /:categories/:title

url: "http://codeville.org.in"
share_image: "/img/logo/codeville_icon.png"
share_desc: "Codeville is a platform for all the hackers and scripters around the world to publish their scripts and utilities, and eventually brag about it. You can pitch your idea and programmers around the world will try to code it for you."
keywords: "codeville, publish scripts, share scripts, hackers, scripter, useful scripts"