name: "Codeville"
markdown: "redcarpet"
highlighter: "pygments"
baseurl: ""
title: "Codeville"
url: "http://codeville.org.in"
share_image: "/img/logo/codeville_icon.png"
share_desc: "Codeville is an open platform to show off your scripting skills, find some useful scripts. It also provides a platform to learn computer courses, practice coding online, solve trivia questions and improve coding skills."