name: "Codeville"
markdown: "redcarpet"
highlighter: "pygments"
baseurl: ""
title: "Codeville"

permalink: /:categories/:title

url: "http://codeville.org.in"
share_image: "/img/logo/codeville_icon.png"
share_desc: "Codeville is a platform for all the hackers and scripters around the world to publish their scripts and utilities, and eventually brag about it. At Codeville language is no bar, nor is the technology. If you have written something useful share it with the world. If you haven't written still we got something for you. You can pitch your idea here and some coder in the other side of the world will try to help you out. :) So overall it is a win-win situation for both."
keywords: "codeville, publish scripts, share scripts, hackers, scripter, useful scripts"